services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data_source/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./data_source/import_reviews.sh:/docker-entrypoint-initdb.d/02_import_reviews.sh:ro
      - ./data_source/processed_datasets:/docker-entrypoint-initdb.d/data/processed_datasets:ro
      - ./data_source/custom_kaggle_datasets:/docker-entrypoint-initdb.d/data/custom_kaggle_datasets:ro
    command:
      - postgres
      - -c
      - max_wal_size=2GB
      - -c
      - checkpoint_timeout=10min
      - -c
      - checkpoint_completion_target=0.7
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 10s
      timeout: 8s
      retries: 5

volumes:
  postgres_data:
    name: postgres_data

networks:
  default:
    name: common-net
    external: true