FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    openjdk-17-jdk-headless \
    gcc \
    g++ \
    make \
    libc-dev \
    python3-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-arm64
ENV PATH="$JAVA_HOME/bin:$PATH"

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--LabApp.token=''", "--LabApp.password=''"]